import "../styles/globals.css";
import Layout from "../components/Layout";
import { NextUIProvider } from "@nextui-org/react";
import Head from "next/head";
import NextNProgress from 'nextjs-progressbar';
import NProgress from 'nprogress';

export default function App({ Component, pageProps }) {
  NProgress.configure({showSpinner:false, trickle:false, minimum:0.01})
  return (
    <>
    <NextNProgress color="#00b1af" height={2}/>
      <Head>
        <title>Library Management System | LMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NextUIProvider>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </NextUIProvider>
    </>
  );
}
